### ISSUE TITLE
enquiry regarding converting opencv coordinates to arcore coordinates

### ISSUE THREAD

**Issue by haojie9777** [qaplqq/hellosceneformaruco#1]
Hi I am trying to do something similar with opencv and arcore. Noticed that you made a comment regarding the title in your code. May I know have u successfully resolved this issue? Thanks.

**Comment by qaplqq** [comment]
Hi, it is hard to transform a location of aruco location of aruco pose-coordination into its corresponding location of arcore coordination.  So, I hard-coded the transformation matrix  Arcore (this matrix is fetched from debugging the program running arcore mobile).  Therefore, though **I am not able to transform it**. I can control the object in Arcore (by monitoring the difference of two locations in aruco)

**Comment by haojie9777** [comment]
Hi! I'm no longer using arcore in my project at the moment, but thanks for replying anyways!
